### ISSUE TITLE
Add raw metadata (from pephub) to the bed page

### ISSUE THREAD

**Issue by khoroshevskyi** [databio/bedhost#121]
![image](https://github.com/databio/bedhost/assets/41573628/f47f4565-8b2e-4eca-84e1-0077c4851783)

**Comment by nleroy917** [comment]
<img width="1169" alt="image" src="https://github.com/databio/bedhost/assets/41063083/0804ac9d-63fb-4c2d-a99c-1bb69e1d8d8e">

here is more metadata for the search results too. However, the `name` is still meaningless. can't figure out what to replace it with, though. I feel like it needs to be something ...

**Comment by khoroshevskyi** [comment]
Fixed in 0.5.0
