### ISSUE TITLE
UI tweaks 

### ISSUE THREAD

**Issue by khoroshevskyi** [databio/bedhost#124]
- [x] Add bedsets list to bed page (divide overview section on 2 and on the right side add one column with bedsets)
- [x] Add info if this bed is universe - to the right to license
- [x] Add annotation to license/bed_type/bed_...
- [x] Remove `global_sample_id` from the top of bedfile page
- [x] Expand overview to 16 elements
- [ ] BedFile page is broken when comming back from api endpoint
- [x] Fix cart download

**Comment by nleroy917** [comment]
> BedFile page is broken when comming back from api endpoint

This one is hard to reproduce and I'm really not sure the cause

**Comment by khoroshevskyi** [comment]
Fixed in 0.5.0
