### ISSUE TITLE
Unexpected application error on search

### ISSUE THREAD

**Issue by nleroy917** [databio/bedhost#134]
**Steps to reproduce:**
1. Navigate to https://bedbase.org/search
2. Type anything into the search bar (e.g. `gse`)
3. Use the nav at the top and click "Text-to-BEDset"
4. Click back to "Text-to-BED"
5. Observer error

Not sure whats going on off the top of my head, but its probably an easy fix

**Comment by khoroshevskyi** [comment]
It seems to be fixed!
