### ISSUE TITLE
Reception for new users

### ISSUE THREAD

**Issue by nsheff** [databio/bedhost#92]
I think it would be good to think about how we can make bedbase more explanatory to a new users. The **about** page is useful, but it's a bit too hard to find as you have to click on the little book icon. How can we make it more immediately clear what bedbase is to a first-time visitor?

I'd like it so that if someone visits, then within 30 seconds they would have an idea of what they can do with bedbase. Then, that could direct them to more detailed information if they want to see it. I'd like to brainstorm on how to make it more approachable. Here are some ideas.

- Some kind of reduced graphic with text on the main page, introducing
- A little 3 minute embedded video clip?
- examples on the front page of live API endpoints users can click to see results
- move the complex search into an 'advanced search' area, and replace with a human-friendly search box (discussed in https://github.com/databio/bedbase/issues/8, https://github.com/databio/bedbase/issues/7). - Move search results off the main page
- I can imagine a few different interfaces: "search by metadata | search by keyword | search by interval | browse by ... "

**Comment by khoroshevskyi** [comment]
Fixed in 0.5.0
